// examples/angular/src/main.ts
import { LotoExample } from "./loto-example";
import { InfinityExample } from "./infinity-example";
import { VolumeExample } from "./volume-example";
import { Component, signal } from "@angular/core";
import { bootstrapApplication } from "@angular/platform-browser";
import type { ChaosLotoOtpProps } from "@sdcorejs/chaos-ui-angular/loto-otp";
import { ChaosProbeAdapter } from "../../../packages/angular/testing/probe";
@Component({
  selector: "app-root",
  standalone: true,
  imports: [ChaosProbeAdapter, LotoExample, InfinityExample, VolumeExample],
  template: `<main class="example">
    <loto-example />
    <infinity-example />
    <volume-example />
    <p class="eyebrow">CHAOS UI / ANGULAR</p>
    <h1>One core.<br />A little chaos.</h1>
    <p>Internal build-pipeline fixture (not public API).</p>
    <p>
      Positional OTP contract: <code>{{ slots }}</code>
    </p>
    @if (visible()) {
      <chaos-probe-adapter [value]="value()" (valueChange)="change($event)" />
    }
    <p data-testid="value">Value: {{ value() }}</p>
    <p data-testid="events">Events: {{ events() }}</p>
    <button (click)="value.set(10)">Set from app</button>
    <button (click)="visible.set(!visible())">Toggle fixture</button>
    <h2>Independent instance</h2>
    <chaos-probe-adapter [(value)]="second" />
  </main>`,
})
class App {
  readonly contract: ChaosLotoOtpProps = { slots: ["0", null, "0"], status: "idle" };
  readonly slots = JSON.stringify(this.contract.slots);
  readonly value = signal(0);
  readonly second = signal(0);
  readonly events = signal(0);
  readonly visible = signal(true);
  change(value: number) {
    this.value.set(value);
    this.events.update((n) => n + 1);
  }
}
bootstrapApplication(App).catch(console.error);

// examples/react/src/main.tsx
import { LotoExample } from "./loto-example";
import { InfinityExample } from "./infinity-example";
import { VolumeExample } from "./volume-example";
import { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";
import type { ChaosLotoOtpProps } from "@sdcorejs/chaos-ui-react/loto-otp";
import { ChaosProbeAdapter } from "../../../packages/react/testing/probe";
import "../../../apps/playground/src/style.css";
const contract: ChaosLotoOtpProps = { slots: ["0", null, "0"], status: "idle" };
function App() {
  const [value, setValue] = useState(0);
  const [events, setEvents] = useState(0);
  const [visible, setVisible] = useState(true);
  return (
    <main className="example">
      <LotoExample />
      <InfinityExample />
      <VolumeExample />
      <p className="eyebrow">CHAOS UI / REACT</p>
      <h1>
        One core.
        <br />A little chaos.
      </h1>
      <p>Internal build-pipeline fixture (not public API).</p>
      <p>
        Positional OTP contract: <code>{JSON.stringify(contract.slots)}</code>
      </p>
      {visible && (
        <ChaosProbeAdapter
          value={value}
          onChaosChange={(e) => {
            setValue(e.detail.value);
            setEvents((n) => n + 1);
          }}
        />
      )}
      <p data-testid="value">Value: {value}</p>
      <p data-testid="events">Events: {events}</p>
      <button onClick={() => setValue(10)}>Set from app</button>{" "}
      <button onClick={() => setVisible((v) => !v)}>Toggle fixture</button>
      <h2>Independent instance</h2>
      <Independent />
    </main>
  );
}
function Independent() {
  const [value, setValue] = useState(0);
  return (
    <ChaosProbeAdapter value={value} onChaosChange={(e) => setValue(e.detail.value)} />
  );
}
createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
