// examples/angular/src/volume-example.ts
import { Component, DestroyRef, inject, signal } from "@angular/core";
import { FormControl, ReactiveFormsModule } from "@angular/forms";
import {
  ChaosVolumeGymComponent,
  type VolumeChangeDetail,
} from "@sdcorejs/chaos-ui-angular/volume-gym";

@Component({
  selector: "volume-example",
  standalone: true,
  imports: [ReactiveFormsModule, ChaosVolumeGymComponent],
  template: `<section class="volume-example">
    <h2>Volume Gym · Angular Reactive Forms</h2>
    <p>FormControl nhận cả thao tác trực tiếp và giá trị thay đổi bởi gravity.</p>
    <chaos-volume-gym
      [formControl]="control"
      [gravity]="gravity()"
      [decayRate]="30"
      [readOnly]="readOnly()"
      (sdChange)="changed($event)"
      (sdCommit)="commits.update(increment)"
    />
    <p>
      Value: <b data-testid="volume-value">{{ value() }}</b> · Changes:
      <b data-testid="volume-changes">{{ changes() }}</b> · Commits:
      <b data-testid="volume-commits">{{ commits() }}</b> · Source:
      <b data-testid="volume-source">{{ source() }}</b>
    </p>
    <p data-testid="volume-form-state">
      Touched: {{ control.touched }} · Disabled: {{ control.disabled }}
    </p>
    <div class="demo-controls">
      <button (click)="control.setValue(73)">Set volume from app</button>
      <button (click)="gravity.set(!gravity())">Toggle volume gravity</button>
      <button (click)="control.disabled ? control.enable() : control.disable()">
        Toggle volume disabled
      </button>
      <button (click)="readOnly.set(!readOnly())">Toggle volume readonly</button>
    </div>
    <h3>Independent model binding (no Forms)</h3>
    <chaos-volume-gym [(model)]="other" [step]="5" />
    <p data-testid="volume-other-model">{{ other() }}</p>
  </section>`,
})
export class VolumeExample {
  readonly control = new FormControl(40, { nonNullable: true });
  readonly other = signal(25);
  readonly gravity = signal(false);
  readonly readOnly = signal(false);
  readonly value = signal(40);
  readonly changes = signal(0);
  readonly commits = signal(0);
  readonly source = signal("none");
  readonly increment = (n: number) => n + 1;
  constructor() {
    const subscription = this.control.valueChanges.subscribe((v) =>
      this.value.set(v),
    );
    inject(DestroyRef).onDestroy(() => subscription.unsubscribe());
  }
  changed(detail: VolumeChangeDetail): void {
    this.changes.update(this.increment);
    this.source.set(detail.source);
  }
}

// examples/react/src/volume-example.tsx
import { useState } from "react";
import {
  ChaosVolumeGym,
  VolumeGym,
  type VolumeChangeSource,
} from "@sdcorejs/chaos-ui-react/volume-gym";

export function VolumeExample() {
  const [value, setValue] = useState(40);
  const [changes, setChanges] = useState(0);
  const [commits, setCommits] = useState(0);
  const [source, setSource] = useState<VolumeChangeSource | "none">("none");
  const [gravity, setGravity] = useState(false);
  const [disabled, setDisabled] = useState(false);
  const [readOnly, setReadOnly] = useState(false);
  return (
    <section className="volume-example">
      <h2>Volume Gym · React controlled</h2>
      <p>Giá trị thuộc ứng dụng; tạ chỉ gửi yêu cầu đổi mức âm lượng.</p>
      <ChaosVolumeGym
        value={value}
        gravity={gravity}
        decayRate={30}
        disabled={disabled}
        readOnly={readOnly}
        onChange={({ value, source }) => {
          setValue(value);
          setSource(source);
          setChanges((n) => n + 1);
        }}
        onCommit={() => setCommits((n) => n + 1)}
      />
      <p>
        Value: <b data-testid="volume-value">{value}</b> · Changes: {" "}
        <b data-testid="volume-changes">{changes}</b> · Commits: {" "}
        <b data-testid="volume-commits">{commits}</b> · Source: {" "}
        <b data-testid="volume-source">{source}</b>
      </p>
      <div className="demo-controls">
        <button onClick={() => setValue(73)}>Set volume from app</button>
        <button onClick={() => setGravity((v) => !v)}>Toggle volume gravity</button>
        <button onClick={() => setDisabled((v) => !v)}>Toggle volume disabled</button>
        <button onClick={() => setReadOnly((v) => !v)}>Toggle volume readonly</button>
      </div>
      <h3>Independent uncontrolled machine</h3>
      <VolumeGym defaultValue={25} step={5} />
    </section>
  );
}
