// packages/angular/testing/probe.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  input,
  output,
} from "@angular/core";
import { registerProbe } from "../../chaos-ui/testing/register.js";
@Component({
  selector: "chaos-probe-adapter",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template:
    '<chaos-internal-probe [value]="value()" (chaos-change)="forward($event)" />',
})
export class ChaosProbeAdapter {
  readonly value = input(0);
  readonly valueChange = output<number>();
  constructor() {
    registerProbe();
  }
  forward(event: Event) {
    this.valueChange.emit(
      (event as CustomEvent<{ value: number }>).detail.value,
    );
  }
}

// packages/react/testing/probe.tsx
import * as React from "react";
import { createComponent, type EventName } from "@lit/react";
import { ChaosProbe } from "../../chaos-ui/testing/probe.js";
import { registerProbe } from "../../chaos-ui/testing/register.js";
const Element = createComponent({
  react: React,
  tagName: "chaos-internal-probe",
  elementClass: ChaosProbe,
  events: {
    onChaosChange: "chaos-change" as EventName<CustomEvent<{ value: number }>>,
  },
});
/** Internal adapter: registration is explicit and lazy, props/events stay in Lit. */
export function ChaosProbeAdapter(props: React.ComponentProps<typeof Element>) {
  React.useEffect(() => {
    registerProbe();
  }, []);
  return <Element {...props} />;
}
